language: node_js
node_js:
  - lts/*
script:
  - echo "Starting deploy script..."
deploy:
  provider: npm
  script: echo "Deploying to npm ..."
  email: "$NPM_EMAIL"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
